# -*- coding: utf-8 -*-
"""Copy of AirBnb Bookings Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MX1lRZs4sTXMSmxS0jwe8z9Hfth5Xzhe

# **Project Name** - **AirBnb Bookings Analysis**

##### **Project Type**    - Exploratory Data Analysis (EDA), Insights & Recommendations
##### **Contribution**    - Individual

# **Project Summary -**

This project analyzes 49,000 Airbnb listings in New York City (2019 data). The dataset contains 16 attributes covering host details, property types, location, pricing, availability, and reviews.

The objective is to **gain business insights** about:

- **Geographical trends** → Where most listings are located.

- **Room types** → Which are most in demand.

- **Pricing patterns** → How prices vary by location & room type.

- **Availability trends** → How often listings are bookable.

- **Customer engagement** → How reviews affect demand.

- **Value of insights:**

- **For guests** → Find affordable & suitable stays.

- **For hosts** → Optimize pricing & availability.

- **For Airbnb** → Improve marketing, trust, and revenue strategies.

# **GitHub Link -**

Provide your GitHub Link here.

# **Problem Statement**

**Airbnb has disrupted the travel industry, but faces challenges such as:**

  - Unbalanced pricing (outliers with unrealistic values).

  - Inconsistent availability across neighborhoods.

  - Varying host performance.

  - Guest trust and engagement issues.

#### **Define Your Business Objective?**

Identify market trends in room types, pricing, and locations.

Detect anomalies in listings (e.g., unrealistic prices/minimum nights).

Understand factors influencing customer demand.

Provide **actionable insights** to optimize pricing, improve host performance, and guide Airbnb’s business strategies.

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
#  Importing essential libraries

# Data handling
import pandas as pd
import numpy as np


# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns

# To ignore warnings for clean output
import warnings
warnings.filterwarnings("ignore")

"""### Dataset Loading"""

# Load Dataset
from google.colab import drive
drive.mount("/content/drive")

file_path = "/content/drive/MyDrive/project 1/Airbnb NYC 2019.csv"
airnb_df = pd.read_csv(file_path)

"""### Dataset First View"""

# Dataset First Look
# data head
airnb_df.head()

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count

# Check the shape of the dataset (rows, columns)
print("dataset contains :", airnb_df.shape[0], "rows and", airnb_df.shape[1], "columns")

"""### Dataset Information"""

# Dataset Info
airnb_df.info()

"""#### Duplicate Values"""

# Dataset Duplicate Value Count

# Count duplicate rows in the dataset
duplicate_count = airnb_df.duplicated().sum()
print("no of duplicate rows :", duplicate_count)

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count

# Count missing values in each column
missing_values = airnb_df.isnull().sum()

# Display only columns with missing values
print("Missing Values per Column:\n", missing_values[missing_values > 0])

# Visualize missing values with heatmap
plt.figure(figsize= (12, 6))
sns.heatmap(airnb_df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values Heatmap",fontsize = 16)
plt.show()

"""### What did you know about your dataset?

**Dataset Overview**

- 48,895 rows and 16 columns

- Mix of numeric & categorical data

- Few missing values (last_review, reviews_per_month, name, host_name)

**No duplicate rows**

- Dataset is clean and ready for analysis (pricing, customer behavior, host performance)

## ***2. Understanding Your Variables***
"""

# Dataset Columns
print(airnb_df.columns)

# Dataset Describe
print(airnb_df.describe())

"""**Variables Description**


- **id** → Unique ID for each listing

- **name** → Name of the listing

- **host_id** → Unique ID for host

- **host_name** → Name of the host

- **neighbourhood_group** → Broad location (e.g., Manhattan)

- **neighbourhood** → Specific neighborhood

- **latitude / longitude** → Location coordinates

- **room_type** → Type of room (Entire home, Private, Shared)

- **price** → Price per night

- **minimum_nights** → Minimum nights to book

- **number_of_reviews** → Total reviews received

- **last_review** → Date of last review

- **reviews_per_month** → Average reviews per month

- **calculated_host_listings_count** → Number of listings per host

- **availability_365** → Days available per year

Answer Here

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.

# Number of unique values in each column
airnb_df.nunique()

"""## **3**. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

# Make a copy of dataset for cleaning
df = airnb_df.copy()

# 1. Remove duplicate rows
df = df.drop_duplicates()

# 2. Handle missing values
# Replace missing 'reviews_per_month' with 0
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)

# Replace missing 'last_review' with 'No Review'
df['last_review'] = df['last_review'].fillna('No Review')

# Replace missing 'name' and 'host_name' with 'Unknown'
df['name'] = df['name'].fillna('Unknown')
df['host_name'] = df['host_name'].fillna('Unknown')

# 3. Remove extreme outliers in 'price' (optional but useful)
# Keep listings with price between 1 and 1000 for better analysis
df = df[(df['price'] > 0) & (df['price'] <= 1000)]

# 4. Reset index after cleaning
df = df.reset_index(drop=True)

# 5. Confirm dataset is ready
print("Rows, Columns after cleaning:", df.shape)
print("Missing values after cleaning:\n", df.isnull().sum())

"""### What all manipulations have you done and insights you found?

**Data Manipulations**

- Loaded and inspected the dataset.

- Handled missing values and converted data types.

- Filtered data, created new features (e.g., price_per_night).

- Grouped, aggregated, and visualized data.

- Detected and handled outliers.







**Insights**

- Manhattan has the highest prices; Staten Island the lowest.

- Entire home/apartment is the most common room type.

- Listings with more reviews are usually popular and pricier.

- Brooklyn has the most listings; Manhattan dominates high-end pricing.

- Higher minimum nights sometimes mean lower price per night.

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

**Solution to Business Objective (Brief):**

To achieve the business objective, I suggest the client to:

**Optimize Pricing:** Use neighbourhood and room-type insights to set competitive, location-based prices.

**Boost Customer Trust:** Encourage hosts to get more reviews by improving service quality and availability.

**Balance Market Segments:** Promote both luxury and budget listings to attract a wide range of travelers.

**Handle Outliers:** Filter unrealistic prices and minimum night stays to ensure data-driven, accurate decisions.

**Data-Driven Strategy:** Use visualization insights to identify demand trends, improve host guidance, and enhance customer experience.


**This will improve bookings, maximize revenue, and strengthen Airbnb’s position in the market.**

## **4. Guiding Questions for** **Analysis**

- Which neighbourhood group has the highest and lowest average prices?
- How do prices vary across different room types?
- Do higher-priced listings receive more or fewer reviews?
- Which neighbourhood group has the highest number of listings?
- What is the distribution of minimum nights?
- What percentage of listings belong to each room type?
- How do average prices change over time (month to month)?
- Which neighbourhood group has the highest and lowest availability?
- How does availability vary with price across room types?
- What are the top 10 most expensive listings in NYC?
- Which numerical features are strongly correlated with each other?
- How do median prices differ across neighbourhood groups?
- Do categorical features like room type and neighbourhood group influence price?
- What are the relationships between price, reviews, minimum nights, and availability?

## ***5. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart 1 – Average Airbnb Price per Neighborhood Group (Bar Chart)
# visualization code

# Handle missing values if needed
airnb_df = airnb_df.dropna(subset=['price', 'neighbourhood_group'])

# Aggregate: average price per neighbourhood_group
avg_price = airnb_df.groupby('neighbourhood_group')['price'].mean().reset_index()

# Plot
plt.figure(figsize=(8,5))
sns.barplot(x='neighbourhood_group', y='price', data=avg_price, palette='viridis')
plt.title('Average Airbnb Price per Neighborhood Group')
plt.xlabel('Neighborhood Group')
plt.ylabel('Average Price ($)')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** Compare average prices across boroughs

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Manhattan is most expensive.

- Staten Island is cheapest.

- Brooklyn falls in the mid-high range.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Positive Impact:** Helps Airbnb balance luxury vs budget markets.

**Negative Insight:** Very high Manhattan prices may discourage budget travelers.

#### Chart - 2
"""

# Chart 2 – Price Distribution by Room Type (Boxplot)

# visualization code

# Handle missing or extreme values
airnb_df = airnb_df[airnb_df['price'] <= 1000]  # Removing extreme outliers

# Plot: Price distribution by room type
plt.figure(figsize=(8,5))
sns.boxplot(x='room_type', y='price', data=airnb_df, palette='Set2')
plt.title('Price Distribution by Room Type')
plt.xlabel('Room Type')
plt.ylabel('Price ($)')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** Compare price ranges across different room types.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Entire homes are priciest.

- Private rooms dominate mid-range.

- Shared rooms are cheapest, least common

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Positive Impact:** Supports both premium and affordable travelers.

**Negative Insight:** Shared rooms show low demand, limiting growth in ultra-budget market.

#### Chart - 3
"""

# Chart 3 – Number of Reviews vs Price (Scatterplot)

# Remove extreme price outliers for better visualization
airnb_df_filtered = airnb_df[airnb_df['price'] <= 1000]
airnb_df_filtered = airnb_df_filtered.reset_index(drop=True)

# Plot: Number of reviews vs. Price
plt.figure(figsize=(8,5))
sns.scatterplot(x='number_of_reviews', y='price', data=airnb_df_filtered, alpha=0.6)
plt.title('Number of Reviews vs. Price')
plt.xlabel('Number of Reviews')
plt.ylabel('Price ($)')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** Check if price impacts customer engagement.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Affordable listings get most reviews.

- Mid-range also performs well.

- High-priced listings get very few reviews.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Positive Impact:** Confirms affordable stays drive guest engagement.

**Negative Insight:** Overpriced luxury listings risk low occupancy.

#### Chart - 4
"""

# Chart - 4 Number of Listings per Neighborhood Group (Countplot / Bar Chart)

# visualization code

# Plot: Count of listings per neighborhood group
plt.figure(figsize=(8,5))
sns.countplot(x='neighbourhood_group', data=airnb_df, palette='pastel')
plt.title('Number of Airbnb Listings per Neighborhood Group')
plt.xlabel('Neighborhood Group')
plt.ylabel('Number of Listings')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** Show distribution of listings across NYC..

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Brooklyn & Manhattan dominate supply.

- Queens moderate.

- Bronx & Staten Island very low.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Positive Impact:** Growth opportunities in underrepresented areas.

**Negative Insight:** Heavy reliance on top 2 boroughs risks market saturation.

#### Chart - 5
"""

# Chart 5 - Distribution of Minimum Nights for Airbnb Listings (Histogram with KDE)

# Remove extreme outliers for better visualization
airnb_df_filtered = airnb_df[airnb_df['minimum_nights'] <= 100]
airnb_df_filtered = airnb_df_filtered.reset_index(drop=True)

# Plot: Distribution of minimum nights
plt.figure(figsize=(8,5))
sns.histplot(airnb_df_filtered['minimum_nights'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Minimum Nights for Airbnb Listings')
plt.xlabel('Minimum Nights')
plt.ylabel('Number of Listings')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** To understand guest stay duration patterns and detect unusual booking behaviors.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

Most listings have a **minimum stay of 1–7 nights.**

A spike also appears around **30 nights**, likely for monthly rentals.

Some listings allow extremely long stays (outliers).

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Positive Impact:**
- Confirms Airbnb demand is dominated by short-term stays, helping hosts optimize for tourists and short visits.

**Negative Insight:**
- Unrealistic outliers (hundreds of nights) distort averages and may mislead pricing/availability strategies.

#### Chart - 6
"""

# Chart 6 (Room Type Distribution – Pie Chart)

#visualization code

# Count listings per room type
room_counts = airnb_df['room_type'].value_counts()

# Plot: Pie chart of room type distribution
plt.figure(figsize=(7,7))
plt.pie(room_counts, labels=room_counts.index, autopct='%1.1f%%', colors=['#ff9999','#66b3ff','#99ff99','#ffcc99'])
plt.title('Distribution of Listings by Room Type')
plt.show()

"""##### 1. Why did you pick the specific chart?

**What it shows:** Share of listings by room type.

##### 2. What is/are the insight(s) found from the chart?

**Insights :**

- Entire homes/apartments are the largest share.

- Private rooms are also significant.

- Shared rooms are very limited.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Positive:** Balance of entire homes (luxury) and private rooms (affordable) attracts diverse guests.

**Negative:** Very few shared rooms → limits budget traveler options.

#### Chart - 7
"""

# Chart - 7 – Reviews per Month Distribution (Histogram)

#visualization code

# Use cleaned df if available; otherwise use airnb_df with NaNs handled
data_for_reviews = airnb_df.copy()
data_for_reviews['reviews_per_month'] = data_for_reviews['reviews_per_month'].fillna(0)

plt.figure(figsize=(8,5))
sns.histplot(data_for_reviews['reviews_per_month'], bins=30, kde=True)
plt.title('Reviews per Month Distribution')
plt.xlabel('Reviews per Month')
plt.ylabel('Number of Listings')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** To check how often listings receive reviews (customer engagement

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Most listings:** 0–2 reviews/month**.

- Few listings: very high review activity

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Business impact:**

**Positive**: Identify popular, trusted listings for promotion.

**Negative:** Many listings with zero reviews may reduce guest trust

#### Chart - 8
"""

# Chart 8 – Average Availability of Listings by Neighborhood Group (Bar Chart)

 #visualization code

# Remove missing values
airnb_df = airnb_df.dropna(subset=['availability_365', 'neighbourhood_group'])

# Aggregate: average availability per neighborhood
avg_availability = airnb_df.groupby('neighbourhood_group')['availability_365'].mean().reset_index()

# Plot
plt.figure(figsize=(8,5))
sns.barplot(x='neighbourhood_group', y='availability_365', data=avg_availability, palette='coolwarm')
plt.title('Average Availability of Listings by Neighborhood Group')
plt.xlabel('Neighborhood Group')
plt.ylabel('Average Availability (Days)')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Reason for choosing a bar chart:**

- To compare how many days listings are available across neighborhoods.
"""



"""##### 2. What is/are the insight(s) found from the chart?

**Insights**:

- Manhattan & Brooklyn → higher average availability.

- Bronx & Staten Island → lower availability

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Business impact**:

**Positive:** Helps optimize booking supply and promote high-availability areas.

**Negative**: Low availability in some areas limits guest options and revenue.

#### Chart - 9
"""

# Chart - 9 Price vs. Availability by Room Type (Scatter Plot)

# visualization

# Filter out extreme price outliers for clarity
airnb_df_filtered = airnb_df[airnb_df['price'] <= 1000]

# Plot: Price vs. Availability by Room Type
plt.figure(figsize=(10,6))
sns.scatterplot(x='availability_365', y='price', hue='room_type', data=airnb_df_filtered, alpha=0.6)
plt.title('Price vs. Availability by Room Type')
plt.xlabel('Availability (Days)')
plt.ylabel('Price ($)')
plt.legend(title='Room Type')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why:** To see how price and availability vary across room types.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Entire homes → higher prices, varied availability.

- Private/Shared rooms → lower prices, moderate availability.

- High-priced listings often less available.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Business impact:**

**Positive:** Helps adjust pricing & availability per room type.

**Negative:** Expensive listings with low availability risk fewer bookings.

#### Chart - 10
"""

# Chart - 10 visualization code

# Filter top 10 expensive listings
top10_expensive = airnb_df.nlargest(10, 'price')

# Plot
plt.figure(figsize=(10,6))
sns.barplot(x='price', y='name', data=top10_expensive, palette='magma')
plt.title('Top 10 Most Expensive Airbnb Listings in NYC')
plt.xlabel('Price ($)')
plt.ylabel('Listing Name')
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why this chart:**
- To highlight the most expensive listings and compare them directly.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- A few listings are priced extremely high.

- These belong mostly to luxury/entire home segments.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Business impact:**

**Positive:** Useful for targeting high-income travelers and luxury marketing.

**Negative:** Big price gap may discourage average travelers.

#### Chart - 11
"""

# Chart - 11 Correlation Heatmap of Numerical Features

# visualization code

# Select numerical columns
num_cols = airnb_df[['price','minimum_nights','number_of_reviews','reviews_per_month','availability_365']]

# Compute correlation
corr = num_cols.corr()

# Plot heatmap
plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlation Heatmap of Airbnb Numerical Features")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why this chart:**
- To quickly see relationships between numerical variables like price, reviews, and availability.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Reviews and reviews/month are strongly related.

- Price has weak correlation with most features.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Business impact:**

**Positive:** Helps focus on review-based insights for demand.

**Negative:** Misusing weak correlations (e.g., price & minimum nights) could lead to poor strategies

#### Chart - 12
"""

# Chart - 12 visualization code

plt.figure(figsize=(8,6))
sns.boxplot(x='neighbourhood_group', y='price', data=airnb_df, showfliers=False, palette="Set2")
plt.title("Price Distribution by Neighbourhood Group")
plt.xlabel("Neighbourhood Group")
plt.ylabel("Price ($)")
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why this chart:**
To compare price ranges and medians across different boroughs.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Manhattan → highest median and widest variation.

- Staten Island & Queens → lower, more stable prices.

- Outliers exist in all groups.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

**Business impact:**

**Positive:** Helps set location-based pricing strategies.

**Negative:** Overpricing in high-demand areas may reduce bookings.

Chosen to show correlations between **numerical and categorical features** together, giving a fuller view of how location and room type relate to price, reviews, and availability.

#### Chart - 13 - Pair Plot
"""

# Pair Plot visualization code

# Select key features for pair plot
pair_cols = ['price','minimum_nights','number_of_reviews','reviews_per_month','availability_365']
sns.pairplot(airnb_df[pair_cols], diag_kind="kde", plot_kws={'alpha':0.5})
plt.suptitle("Pair Plot of Key Numerical Features", y=1.02)
plt.show()

"""##### 1. Why did you pick the specific chart?

**Why this chart:**
- To explore relationships and distributions among multiple numerical variables in one view.

##### 2. What is/are the insight(s) found from the chart?

**Insights:**

- Price shows extreme outliers.

- reviews/month aligns with total reviews.

- Minimum nights are highly skewed.

## **6. Solution to Business Objective**

- **Optimize Pricing** → Leverage neighborhood and room-type insights to set competitive, dynamic prices.

- **Boost Trust** → Encourage hosts to collect more reviews and showcase top-rated listings.

- **Balance Segments** → Promote both luxury and budget stays to attract a wider range of travelers.

- **Handle Outliers** → Remove unrealistic prices and minimum-night requirements for cleaner, more reliable insights.

- **Data-Driven Strategy** → Apply EDA insights to guide hosts and support smarter decision-making.

# **Conclusion**

**Conclusion**

- Gained clear insights on neighborhoods, pricing, and reviews.  
- Outliers in price & minimum nights were key challenges.  
- Resolved using filtering and capping.  
- Insights help Airbnb optimize pricing, boost host engagement, and grow revenue.  

**Final Note:** These insights can guide Airbnb in refining strategies for both budget and luxury travelers, ensuring sustainable growth in NYC.

### ***Hurrah! You have successfully completed your EDA Capstone Project !!!***
"""